POST http://localhost:8080/auth/reissue
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMiIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2OTI1MDQ1Nzh9.s9UFjuulXHteO5MvolX2MkREEDuguOsLXY5-Wc5m9b4",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTMxMDc1Nzh9.BUncatNkjBfB994LoBqUnGlJ0HZkc_Cn9RDGZme1IYA"
}